openapi: 3.0.1
info:
  title: SampleAPI
  description: API Definition of SampleAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/base
paths:
  /:
    get:
      responses:
        default:
          description: Default response
